apiVersion: apps/v1
kind: Deployment
metadata:
  name: cndcdjn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cndcdjn
  template:
    metadata:
      labels:
        app: cndcdjn
    spec:
      containers:
      - image: okteto.dev/cndcdjn:latest
        name: cndcdjn
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b53ceeb7-c386-4ac4-94b7-b19f4d33d466"
        - name: Vless_Path
          value: "/vl5cbchfd55"
        - name: Vmess_UUID
          value: "b53ceeb7-c386-4ac4-94b7-b19f4d33d466"
        - name: Vmess_Path
          value: "/vmcdscbds666"
        - name: Share_Path
          value: "/v2link"
